Adjust calculation of child frame position to work on more backends
masm11/emacs pull request #47
Opened 2020-08-23 12:26 UTC by fejfighter

* src/pgtkterm.c (x_set_offset): rework position calculations

2020-08-23 12:26 UTC, fejfighter commented
fixes #46

2020-08-24 02:55 UTC, fejfighter commented
I might have a better method for this, as it stands it's works well on X and wayland, but not broadway.
This would imply that I am missing something

2020-08-24 12:33 UTC, fejfighter commented
I think the broadway issue is related to zoom of some sort.

the "better method" involved `gtk_widget_translate_coordinates ` which appeared to do nothing from all examples found

2020-08-27 16:11 UTC, masm11 requested changes
please fix coding style.

2020-08-27 16:11 UTC, masm11 commented on src/pgtkterm.c
> +      GdkWindow *gw = gtk_widget_get_window(w);
could you put a space after the function name?

2020-08-27 16:11 UTC, masm11 commented on src/pgtkterm.c
> +      gdk_window_get_frame_extents(gw, &rect);
could you put a space after the function name?

2020-08-27 22:59 UTC, fejfighter commented
@masm11 I'll add fixes for #48 and #49 to this pull request

2020-09-16 09:43 UTC, fejfighter commented
superseded by #51

2020-09-22 09:44 UTC, closed without merging